language: node_js

node_js:
  - 7

cache:
  yarn: true

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn run coverage

branches:
  only:
  - develop

notifications:
  email:
    recipients:
      - jorgegonzalezperez@outlook.com
    on_success: never # default: change
    on_failure: always # default: always