language: node_js

node_js:
  - 8.10.0
  - 9.8.0

cache:
  yarn: true

install:
  - yarn

script:
  - yarn start

git:
  depth: 3

branches:
  only:
  - master
  - develop

notifications:
  email:
    recipients:
      - jorgegonzalezperez@outlook.com
    on_success: never # default: change
    on_failure: always # default: always