version: 2
jobs:
    build:
        working_directory: ~/tictactoe-with-nestjs
        docker:
            - image: circleci/node:8-browsers
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn
            - run:
                name: Run Tests
                command: yarn test
destination: coverage